// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB-1Xnf4Y-eh630Pvh76s3GLRjDMIOYM2s',
    appId: '1:582571123867:web:91d8a7bcdea020b47b923e',
    messagingSenderId: '582571123867',
    projectId: 'once-in-mind',
    authDomain: 'once-in-mind.firebaseapp.com',
    storageBucket: 'once-in-mind.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCiicGmeFgB5HCQgOk8UgB0vcdoetZFfX0',
    appId: '1:582571123867:android:80d70cda59b05a7e7b923e',
    messagingSenderId: '582571123867',
    projectId: 'once-in-mind',
    storageBucket: 'once-in-mind.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyByKmnXXb52jLENwfNudgUkorMEidrgw6g',
    appId: '1:582571123867:ios:104678d8b5e4fdb57b923e',
    messagingSenderId: '582571123867',
    projectId: 'once-in-mind',
    storageBucket: 'once-in-mind.firebasestorage.app',
    iosBundleId: 'com.example.onceinmind',
  );
}
